name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Check fmt
        run: deno fmt --check

      - name: Check lint
        run: deno lint

      - name: Check types
        run: deno check

      - name: Run tests
        run: deno task test
